/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ColorPalette {
        "colors": string;
    }
    interface ColorPaletteRow {
        "color": string;
    }
}
declare global {
    interface HTMLColorPaletteElement extends Components.ColorPalette, HTMLStencilElement {
    }
    var HTMLColorPaletteElement: {
        prototype: HTMLColorPaletteElement;
        new (): HTMLColorPaletteElement;
    };
    interface HTMLColorPaletteRowElement extends Components.ColorPaletteRow, HTMLStencilElement {
    }
    var HTMLColorPaletteRowElement: {
        prototype: HTMLColorPaletteRowElement;
        new (): HTMLColorPaletteRowElement;
    };
    interface HTMLElementTagNameMap {
        "color-palette": HTMLColorPaletteElement;
        "color-palette-row": HTMLColorPaletteRowElement;
    }
}
declare namespace LocalJSX {
    interface ColorPalette {
        "colors"?: string;
    }
    interface ColorPaletteRow {
        "color"?: string;
    }
    interface IntrinsicElements {
        "color-palette": ColorPalette;
        "color-palette-row": ColorPaletteRow;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "color-palette": LocalJSX.ColorPalette & JSXBase.HTMLAttributes<HTMLColorPaletteElement>;
            "color-palette-row": LocalJSX.ColorPaletteRow & JSXBase.HTMLAttributes<HTMLColorPaletteRowElement>;
        }
    }
}
