/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ColorPalette {
        "colors": string;
        "controls": boolean;
        "title": string;
    }
    interface ColorPaletteRow {
        "color": string;
    }
    interface InputToggle {
        "toggleId": string;
        "toggleLabel": string;
    }
}
declare global {
    interface HTMLColorPaletteElement extends Components.ColorPalette, HTMLStencilElement {
    }
    var HTMLColorPaletteElement: {
        prototype: HTMLColorPaletteElement;
        new (): HTMLColorPaletteElement;
    };
    interface HTMLColorPaletteRowElement extends Components.ColorPaletteRow, HTMLStencilElement {
    }
    var HTMLColorPaletteRowElement: {
        prototype: HTMLColorPaletteRowElement;
        new (): HTMLColorPaletteRowElement;
    };
    interface HTMLInputToggleElement extends Components.InputToggle, HTMLStencilElement {
    }
    var HTMLInputToggleElement: {
        prototype: HTMLInputToggleElement;
        new (): HTMLInputToggleElement;
    };
    interface HTMLElementTagNameMap {
        "color-palette": HTMLColorPaletteElement;
        "color-palette-row": HTMLColorPaletteRowElement;
        "input-toggle": HTMLInputToggleElement;
    }
}
declare namespace LocalJSX {
    interface ColorPalette {
        "colors"?: string;
        "controls"?: boolean;
        "title"?: string;
    }
    interface ColorPaletteRow {
        "color"?: string;
    }
    interface InputToggle {
        "toggleId"?: string;
        "toggleLabel"?: string;
    }
    interface IntrinsicElements {
        "color-palette": ColorPalette;
        "color-palette-row": ColorPaletteRow;
        "input-toggle": InputToggle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "color-palette": LocalJSX.ColorPalette & JSXBase.HTMLAttributes<HTMLColorPaletteElement>;
            "color-palette-row": LocalJSX.ColorPaletteRow & JSXBase.HTMLAttributes<HTMLColorPaletteRowElement>;
            "input-toggle": LocalJSX.InputToggle & JSXBase.HTMLAttributes<HTMLInputToggleElement>;
        }
    }
}
